language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
   global:
        # Doctr deploy key for Fratorhe/ramanpy
        - secure: "AXzahdzPhMq5LGqmSPtHwvM0XLS3mROSF1r2+iAzvZznGrd4z2LOFjOCKvOtI9v+mSTW5zlhvPpyJfytPr3sTeNtn+Azg+p1A0s0CnJo7c4z8380RtJmreRzqqhjyAQDezKvoTPX2CLWAyyt/6he03j8dTb/Jk7RRS22nIasEAfVh+AV0F7xAt5b/OWO+ApZrti/YlnUj/BKc5Xhk/WIBb9+IM4OWXApcxKyHEbUDgmhs3c8SzcwV8yAQuV3RQqQkM/bxfbVhjj9wzmXQU7vDHzI/TBhs36h+iOS6QDkTmXQvXkBjbdvtTRxg6hSmnZHeVaT5F+J56QE9Xjin4UDMJ8H5WCD2AGz7eC9wUZTOO66cN4dBu1NswqGgo2ZnRryQcMP/+J+z+trHaWbelrsscUdCdksZ3ypnEnoCOcGN4icM4B4lgU9RnqX49sOux/9XrgOHkYHRd9OCrtPrcuPD6axSh+YE1rT25DzMnlrnWwXLvU1uktgIWe4MMj3bgXp4NDRZAW5UXkfImG0Y2KAUzZW2mY5Jk9EQTnQZa79xfKasVb8fQXJ6zl1quEtY72EIDudQNcamk3RAre7rbbMZR8EqWVQv4p5k7lDoKCu+r2rdgXSVnlufadNP5an57YNH6LVIJ6iQX8/MfxSQyALQTVVlpXdcw6ACOiQBAH9mz0="

install:
  # The versions of pip and numpy that come pre-installed are often too old and
  # can cause problems. Upgrade them.
  - pip install --upgrade pip numpy
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
  - flake8  # Enforce code style ('relaxed' line length limit is set in .flake8 config file).
  - set -e
  - make -C docs html  # Build the documentation.
  - pip install doctr
  - doctr deploy --built-docs docs/build/html .


