language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
   global:
        # Doctr deploy key for Fratorhe/ramanpy
        - secure: "jwWt0EpRpbzyOvRlZpxGkZFdD2iTGAAiXHLU0G77ltD22UGym5Eonrnb4mLR9g5e3j6oStreJX9IgEYHlju55GG8EzvCRNH2tTWMP
        NtOtMpQLBQtUY2GZ/509xrIdKahHvMuO7nUB7FaPzldOLn8qlX6UHl6eYmTmCqzHwXX0J2iSQ+Q3KpouulJX1r5CnCCplbnjjQS9MLoOSJPP2eJ/
        5PC63Wt4rDi+EuOjwBz6kn6SDn+0cSb6Zp+og1Hwr8zDZYI8G38CI9f/TEP+xFUmiiIfPyRWY3FK2s8CPATN7NWw0/c2OUUYHj0R0A/7LMJxxi/n
        QOBYbKhdcpc+n6HR5p29p4tvxNDayuJ2hupCfArdK6W9PMDxhDempOSN6rJQe/YeTCnGpN/mBzBlmLuyXwjcvN9M7ueG+pHuanmwU2gbnS0V97lt
        G6q2hzHBRqnFkFhTU/U+WOtbfMyG9CAYtHI66Wq/jOeQfR6QlFhc+4iL8pvKKML/NRsYH0meyuKBy9VbBUYKzbqX7qvEXachFR6GfIIcUwUhDLKX
        ewBDg2yeYt380HAI+TlFf8HpfAwVtAoXbT1R7BI19NPappq1S/NdijlZxR64YEX/j5R7ZyzAD86OXtE++jfD15n8pjx+Bmc93PtqnnUqCbBsrhSm
        /UXBpsrBn7I4hq7lK3VTRs="

install:
  # The versions of pip and numpy that come pre-installed are often too old and
  # can cause problems. Upgrade them.
  - pip install --upgrade pip numpy
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.
#  - flake8  # Enforce code style ('relaxed' line length limit is set in .flake8 config file).
  - set -e
  - make -C docs html  # Build the documentation.
  - pip install doctr
  - doctr deploy --built-docs docs/build/html .


